### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by toshibochan** [NorthernMan54/homebridge-heyu#5]
I'm looking to control my x10 devices using X10 R.F. PC Transceiver (CM19A), but I don't know nothing about coding. Any chance you can make homebridge for CM19A?
https://www.amazon.com/X10-R-F-PC-Transceiver-CM19A/dp/B0027RMIAO

**Comment by NorthernMan54** [comment]
My existing plugin works by issuing commands to actually turn on and off the lights.  If you saw the commands it would look like

heyu on A5
heyu off A5

If you know what the Linux commands are for the CM19a, it is trivial to change.  If you look at the code base, a person added the CM17A, and a similar pattern could be used for the CM19A.

As heyu does not support the CM19A is there a similar Linux program for to control it?

The other requirement for the plugin, is the heyu configuration file, x10.conf, which defines the accessories, you could easily create this.

**Comment by toshibochan** [comment]
This have the code for Linux 
https://sourceforge.net/projects/mochad/files/

**Comment by NorthernMan54** [comment]
This doesn't look that complicated, and may even be feasible without changing the plugin.  If you install the package and created the command line control except did this instead of the example.

echo "pl $2 $1 $3" | nc localhost 1099

And called the file heyu

You should able to test it with the commands that heyu generates.

heyu on A1
heyu off A1
heyu dim A1 2
heyu bright A1 2

If that works then the plugin will work once you create the heyu config file x10.conf and place it in /etc/heyu/
