### ISSUE TITLE
x10 with Heyu Unable to send address bytes

### ISSUE THREAD

**Issue by tommyd75** [NorthernMan54/homebridge-heyu#7]
I know this is more relating to heyu, but I keep getting this error when I try to manually send an x10 on command to K9, has anyone ever seen this error?
"Unable to send address bytes"
See below for what happens when I run heyu info

pi@raspberrypi:~ $ heyu info
Heyu version 2.10
Configuration at /etc/heyu/x10.conf
Powerline interface on /dev/ttyS0
Firmware revision Level = 1
Interface battery usage = Unknown
Raw interface clock: Wed, Day 290, 19:42:10
(--> Civil Time: Wed 18 Oct 2017   20:42:10 CDT)
No schedule has been uploaded by Heyu.
Housecode = K
0 = off, 1 = on,               unit  16.......8...4..1
Last addressed device =       0x0000 (0000000000000000)
Status of monitored devices = 0x0000 (0000000000000000)
Status of dimmed devices =    0x0000 (0000000000000000)
pi@raspberrypi:~ $ heyu on k9
Unable to send address bytes

**Comment by NorthernMan54** [comment]
Where you aware that heyu’s issue log is here

https://github.com/HeyuX10Automation/heyu

You could try posting there as well.

**Comment by tommyd75** [comment]
Thanks I will try there, I have been trying it with a IBM Homedirector version and a RCA version of the CM11 but they gave the same error, but just tried with a XTB232 and it works fine. Must be something specific to those other devices.

**Comment by NorthernMan54** [comment]
And I tried with my cm11, and it was fine as well.  I also looked at the code, and their is a verbose mode -v that gives more debug info into the issue.  But with all that said, why not just leave k9 out of your setup?

**Comment by tommyd75** [comment]
It does it with any address. I will try verbose Mode  and see what it shows. Thanks again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by npaisnel** [comment]
Anyone still have thoughts on this.

I had this "Unable to send address bytes" error on my system after it failed to work.

I had heyu set up on a RPi with HA-Bridge and integrated with Alexa.

Went to bed a few nights ago.."Everything Off" worked bia Alexa..next morning .nothing .  Alexa working all good there.

SSH'd in to the RPi and tried issuing commands like 

heyu ON A1

and get the responsee 

Unable to send address bytes

Tried all sorts of commands..heyu Info,heyu upload, etc etc..all fail 

Other commands issued at SSH terminal

`pi@x10:/etc/heyu $ heyu info
exread(): write failed
exread(): write failed
exread(): write failed
Invalid status response (was 0 bytes instead of 14)
HEYU: No response from the CM11A on /dev/ttyUSB0
Program exiting.

pi@x10:/etc/heyu $ heyu upload
Heyu directory /etc/heyu/ must be writable - quitting.
pi@x10:/etc/heyu $
`
I just checked permissions of etc/heyu

drwxrwxrwx 3 root root 4096 Apr 8 07:58 heyu

the etc/heyu directory is full of tmp files
named heyu.xxxx.tmp
zero bite serial numbered files
New one created each time a command issued

Any clues what this might be?

Been working fine for years..

**Comment by keithws** [comment]
Seems like your CM11A may have locked up or died or your USB to Serial adapter. Try unplugging one or both, waiting 15 seconds, and plug it back in. Also, try running heyu in verbose mode with ‘heyu -v ON A1’

**Comment by npaisnel** [comment]
Has been unplugged for a few days

Tried new batteries too

here is what verbose mode gives


pi@x10:~ $ heyu -v On b1
Version:2.11-rc3
Searching for '/home/pi/.heyu/x10config'
Searching for '/etc/heyu/x10.conf'Found configuration file '/etc/heyu/x10.conf'
Reading Heyu configuration file '/etc/heyu/x10.conf'
Usage: heyu [options] <command>  (Enter 'heyu help' for commands.)


Without the -v option

pi@x10:~ $ heyu on b1
Unable to send address bytes

pi@x10:~ $

**Comment by npaisnel** [comment]
pi@x10:~ $ heyu info
exread(): write failed
exread(): write failed
exread(): write failed
Invalid status response (was 0 bytes instead of 14)
HEYU: No response from the CM11A on /dev/ttyUSB0
Program exiting.
pi@x10:~ $

**Comment by npaisnel** [comment]
I have confirmed that the USB port itself works by the fact that the Pi also has an RTL-SDR receiver stick on it, which works perfect 
Swapped USB ports and no change.


I do also have a second Euro Style plug CM11 with the different cable.   It has a serial cable and adapter, as opposed to the all in one cable.

That CM11 with different cable gives same error too...... hmmm

so both CM11’s failed or Pi SD card corruption perhaps ?

Would that explain the write error ?

**Comment by npaisnel** [comment]
here is another set of responses with the -v option



pi@x10:~ $ heyu -v info
Version:2.11-rc3
Searching for '/home/pi/.heyu/x10config'
Searching for '/etc/heyu/x10.conf'
Found configuration file '/etc/heyu/x10.conf'
Reading Heyu configuration file '/etc/heyu/x10.conf'
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyUSB0'
Trying to lock (/var/lock/LCK..heyu.write.ttyUSB0)
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyUSB0'
/var/lock/LCK..heyu.write.ttyUSB0 is locked
Alert acks are 0x52, 0x12, 0x42
lockpid: Checking for file '/var/lock/LCK..heyu.relay.ttyUSB0'
lockpid: Checking for file '/var/lock/LCK..heyu.relay.ttyUSB0'
There was already a relay running (pid = 745)
xwrite() called, count=1
exread(): write failed
xread() called, count=14, timeout = 3
Alarm - timeout
xread() returning 0 bytes
re checking for poll 
xread() called, count=1, timeout = 2
Alarm - timeout
xread() returning 0 bytes
re entering get status 
xwrite() called, count=1
exread(): write failed
xread() called, count=14, timeout = 3
Alarm - timeout
xread() returning 0 bytes
re checking for poll 
xread() called, count=1, timeout = 2
Alarm - timeout
xread() returning 0 bytes
re entering get status 
xwrite() called, count=1
exread(): write failed
xread() called, count=14, timeout = 3
Alarm - timeout
xread() returning 0 bytes
Invalid status response (was 0 bytes instead of 14)
HEYU: No response from the CM11A on /dev/ttyUSB0
Program exiting.
lockpid: Checking for file '/var/lock/LCK..heyu.write'
pi@x10:~ $ 



Alos 

pi@x10:~ $ heyu -v upload
Version:2.11-rc3
Searching for '/home/pi/.heyu/x10config'
Searching for '/etc/heyu/x10.conf'
Found configuration file '/etc/heyu/x10.conf'
Reading Heyu configuration file '/etc/heyu/x10.conf'
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyUSB0'
Trying to lock (/var/lock/LCK..heyu.write.ttyUSB0)
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyUSB0'
/var/lock/LCK..heyu.write.ttyUSB0 is locked
Alert acks are 0x52, 0x12, 0x42
lockpid: Checking for file '/var/lock/LCK..heyu.relay.ttyUSB0'
lockpid: Checking for file '/var/lock/LCK..heyu.relay.ttyUSB0'
There was already a relay running (pid = 745)
Heyu directory /etc/heyu/ must be writable - quitting.
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyUSB0'
munlock: Unlink file '/var/lock/LCK..heyu.write.ttyUSB0'
pi@x10:~ $ 




I see that error about etc/heyu needing to be writeable

yet if i do an ls -l  I get 
drwxrwxrwx 3 root root    4096 Apr  9 09:12 heyu

so to me that says it is writeable, no ?


If i look in that directory

pi@x10:/etc $ cd heyu

pi@x10:/etc/heyu $ ls -l
total 76
-rw-r--r-- 1 pi     pi          0 Apr  9 01:32 heyu.19508.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 01:33 heyu.19565.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 01:38 heyu.20219.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 09:10 heyu.22519.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 01:58 heyu.22607.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 01:58 heyu.22666.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 09:11 heyu.22673.tmp
-rw-r--r-- 1 pi     pi          0 Apr  9 09:12 heyu.22875.tmp
-rw-r--r-- 1 root   root        0 Apr  9 02:49 heyu.28997.tmp
-rw-r--r-- 1 pi     pi          0 Apr  8 08:49 heyu.858.tmp
-rw-rw-rw- 1 pi     pi          0 Apr  8 08:47 heyu.log.ttyUSB0
-rw-rw-rw- 1 pi     pi      20480 Mar 22 07:00 heyu.log.ttyUSB0.1
-rw-rw-rw- 1 pi     pi       2492 Mar  8 04:10 heyu.log.ttyUSB0.3.gz
-rw-rw-rw- 1 pi     pi       2320 Feb 28 06:10 heyu.log.ttyUSB0.4.gz
-rw-rw-rw- 1 pi     pi       1993 Feb 14 04:10 heyu.log.ttyUSB0.5.gz
-rw-rw-rw- 1 pi     pi       2480 Jan  1 08:39 report.txt
-rwxrwxrwx 1 nobody nogroup  1941 Feb  5 08:23 x10.conf
-rwxrwxrwx 1 pi     pi       1024 Jan  1 08:39 x10image
-rw-rw-rw- 1 pi     pi       1024 Oct  3  2018 x10image.check
-rw-rw-rw- 1 pi     pi       3584 Oct  3  2018 x10image.hex
-rwxrwxrwx 1 pi     pi         38 Jan  1 08:39 x10macroxref
-rw-rw-rw- 1 pi     pi         38 Oct  3  2018 x10macroxref.check
-rw-rw-rw- 1 root   root      173 Jan  1 08:39 x10record
-rw-rw-rw- 1 pi     pi        173 Oct  3  2018 x10record.check
-rwxrw-rw- 1 pi     pi        260 Jan 12  2019 x10.sched
-rwxrwxrwx 1 pi     pi          0 Apr  8 08:47 x10state


See all the tmp files.
Each time a command is issued (like heyu on a1)  a new temp file is created.

I have two CM11's
a standard CM11 to serial cable and two serial USB adapters, plus the integrated cable.
Will try combinations of them today on a Windows machine, a single Appliance module and the CM11 on a single power strip.  Go back to basics.  see if I can get windows to drive either of them

**Comment by keithws** [comment]
The verbose output was helpful. This line caught my eye:

There was already a relay running (pid = 745)

Looks like a heyu relay process is already running. It might be stuck. I’d try heyu stop and then heyu start. Or, you can try cleaning up to processes manually, kill 745. Or, it might be easiest to just restart the system.

**Comment by npaisnel** [comment]
Thinking that verbose mode may try to start the relay ?

it has been manually rebooted more times than I can remember now,since thus issue started, so that may be a false clue, as this issue just appeared  randomly one night after the system had been running for months, and in that same config for years.


Also.  
heyu On a1

and 

heyu -v On A1

both produce different results 

using the verbose option, heyu does not attempt to action the Command

**Comment by npaisnel** [comment]
Well

found the issue.  SD Card was Full !


I got a new Cm12 and that still did not work.
So wanted to copy a few config files to the pishare folder that I created, that is visible across the network via smb, before I rebuilt the system

No files would copy to it...no disk space error message.

That is the total issue...Card was full 

Still getting a random files created in heyu folder.   Named serially ITG 4 digits.....heyu.4501.tmp 
They get created in the heyu directory and not deleted

why does heyu create these tmp files in /etc/heyu but not delete them?

**Comment by keithws** [comment]
I’m glad you found the issue and it was a simple software fix. Odd things start happening when a system starts running out of disk space.

I’m not sure about those tmp files. You might ask on the heyu project directly. If I remember correctly, the path to tmp files is set during compile time, so heyu may expect it to be /tmp and heyu may expect the system to remove tmp files upon reboot. I’m am not sure. Just guessing.

**Comment by npaisnel** [comment]
When the system has plenty BoF space, the temp files do not appear...

I did have the question on the heyu project too.
